---
excalidraw_container_name: excalidraw
excalidraw_app_path: "{{ app_path }}/excalidraw"
excalidraw_image: excalidraw/excalidraw
# renovate: datasource=docker depName=excalidraw/excalidraw
excalidraw_version: "latest"
excalidraw_port: "8082"
